# Generated by Django 5.2.7 on 2026-03-15 15:44

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_fsm
from django.conf import settings
from django.db import migrations, models

import photition_api.utils.upload_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Photo",
                        upload_to=photition_api.utils.upload_file.uploaded_file_path,
                        verbose_name="Photo",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title", max_length=50, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description",
                        max_length=1000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Updated at", verbose_name="Updated at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created at",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "is_allowed",
                    models.BooleanField(
                        default=False, help_text="Is allowed", verbose_name="Is allowed"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Is deleted", verbose_name="Is deleted"
                    ),
                ),
                (
                    "will_deleted_in",
                    models.DateTimeField(
                        blank=True,
                        help_text="Will deleted in",
                        null=True,
                        verbose_name="Will deleted in",
                    ),
                ),
                (
                    "prev_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Previous photo",
                        null=True,
                        upload_to="",
                        verbose_name="Previous photo",
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        help_text="State",
                        max_length=50,
                        verbose_name="State",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Photo",),
                "verbose_name_plural": "Photos",
            },
        ),
        migrations.CreateModel(
            name="PhotitionUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Avatar",
                        null=True,
                        upload_to=photition_api.utils.upload_file.uploaded_file_path,
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PhotoStats",
            fields=[
                (
                    "photo_id",
                    models.OneToOneField(
                        db_column="photo_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="stats",
                        related_query_name="stat",
                        serialize=False,
                        to="photition_models.photo",
                    ),
                ),
                ("comment_count", models.IntegerField()),
                ("vote_count", models.IntegerField()),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="photo",
            name="author",
            field=models.ForeignKey(
                help_text="Author",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                related_query_name="photo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Comment text", max_length=100, verbose_name="Comment"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created at",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Updated at", verbose_name="Updated at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Is deleted", verbose_name="Is deleted"
                    ),
                ),
                (
                    "answer_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Answer to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        related_query_name="answer",
                        to="photition_models.comment",
                        verbose_name="Answer to",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Author",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        related_query_name="comment",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "belongs_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="belongs",
                        related_query_name="belong",
                        to="photition_models.comment",
                        verbose_name="Belongs to",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        help_text="Photo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        related_query_name="comment",
                        to="photition_models.photo",
                        verbose_name="Photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Message",
                        max_length=100,
                        null=True,
                        verbose_name="Message",
                    ),
                ),
                (
                    "numeric_data",
                    models.IntegerField(
                        blank=True,
                        help_text="Numeric data",
                        null=True,
                        verbose_name="Numeric data",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created", verbose_name="Created"
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("GLOBAL", "Global"),
                            ("NEW_VOTE", "New Vote"),
                            ("VOTE_DELETED", "Vote Deleted"),
                            ("NEW_COMMENT", "New Comment"),
                            ("COMMENT_WILL_DELETED", "Comment Will Deleted"),
                        ],
                        default="GLOBAL",
                        help_text="Event",
                        max_length=100,
                        verbose_name="Event",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        help_text="Initiator",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiator_notices",
                        related_query_name="initiator_notice",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Initiator",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        help_text="Photo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notices",
                        related_query_name="notice",
                        to="photition_models.photo",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="Recipient",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        related_query_name="notice",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notice",
                "verbose_name_plural": "Notices",
            },
        ),
        migrations.CreateModel(
            name="NoticeStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notice_statuses",
                        related_query_name="notice_status",
                        to="photition_models.notice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhotitionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_token", models.TextField(unique=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        related_query_name="session",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="photition_models.photo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="photo",
            name="votes",
            field=models.ManyToManyField(
                through="photition_models.Vote", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
